mi_gestor/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'mi_gestor'

urlpatterns = [
    path('', views.index, name='index'),
    path('home/', views.home, name='home'),
    path('ingresar_presupuesto/', views.ingresar_presupuesto, name='ingresar_presupuesto'),
    path('agregar_gasto/', views.agregar_gasto, name='agregar_gasto'),
    path('eliminar_gasto/<int:gasto_id>/', views.eliminar_gasto, name='eliminar_gasto'),
    path('meses_previos/', views.meses_previos, name='meses_previos'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

myapps/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('mi_gestor/', include('mi_gestor.urls')),
    path('admin/', admin.site.urls),
]

mi_gestor/models.py
import datetime
from django.db import models
from django.contrib.auth.models import User


class PresupuestoMensual(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    fecha = models.DateField(null=True)
    cantidad = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"Presupuesto de {self.usuario.username} - {self.fecha.strftime('%B %Y')}"


class Categoria(models.Model):
    nombre = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.nombre


class GastoMensual(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    fecha = models.DateField()
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE, null=True, blank=True, default=None)
    descripcion = models.CharField(max_length=100)
    cantidad = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"Gasto de {self.usuario}"

mi_gestor/forms.py
from django import forms
from .models import PresupuestoMensual, Categoria, GastoMensual


class PresupuestoForm(forms.ModelForm):
    class Meta:
        model = PresupuestoMensual
        fields = ['fecha', 'cantidad']
        widgets = {
            'fecha': forms.DateInput(attrs={'type': 'date'})
        }


class AgregarGastoForm(forms.ModelForm):
    
    nueva_categoria = forms.CharField(max_length=50, required=False)

    class Meta:
        
        model = GastoMensual
        fields = ['fecha', 'categoria', 'nueva_categoria', 'descripcion', 'cantidad']
        widgets = {
            'fecha': forms.DateInput(attrs={'type': 'date'})
        }

    def __init__(self, *args, **kwargs):
        
        super().__init__(*args, **kwargs)
        self.fields['categoria'].queryset = Categoria.objects.all()
    
    def clean(self):
        
        cleaned_data = super().clean()
        nueva_categoria = cleaned_data.get('nueva_categoria')
        if nueva_categoria:
            categoria_nueva, _ = Categoria.objects.get_or_create(nombre=nueva_categoria)
            cleaned_data['categoria'] = categoria_nueva
        return cleaned_data

mi_gestor/views.py
import matplotlib.pyplot as plt
import datetime
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import authenticate, login
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Sum

from .forms import PresupuestoForm, AgregarGastoForm
from .models import PresupuestoMensual, Categoria, GastoMensual


def index(request):
    
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, '¡Inicio de sesión exitoso!')
            print('¡Inicio de sesión exitoso!')
            return redirect('mi_gestor:home')
        else:
            messages.error(request, 'Usuario o contraseña incorrectos.')
            print('¡Inicio de sesión fallido!')

    return render(request, 'index.html')


@login_required
def home(request):

    mes_actual = datetime.date.today().replace(day=1)

    try:
        presupuesto_mensual = PresupuestoMensual.objects.get(usuario=request.user, fecha=mes_actual)
        presupuesto_mes_actual = presupuesto_mensual.cantidad
    except PresupuestoMensual.DoesNotExist:
        presupuesto_mes_actual = 0

    gastos_mes_actual = GastoMensual.objects.filter(usuario=request.user, fecha__month=mes_actual.month, fecha__year=mes_actual.year).order_by('fecha')
    total_mes_actual = round(gastos_mes_actual.aggregate(total_mes=Sum('cantidad'))['total_mes'] or 0, 2)

    diferencia = presupuesto_mes_actual - total_mes_actual
    
    presupuesto_url = '/ingresar_presupuesto/'
    agregar_gasto_url = '/agregar_gasto/'

    return render(request, 'home.html', {
        'presupuesto_url': presupuesto_url,
        'agregar_gasto_url': agregar_gasto_url,
        'gastos': gastos_mes_actual,
        'presupuesto_mes_actual': presupuesto_mes_actual,
        'total_mes_actual': total_mes_actual,
        'diferencia': diferencia,
        'mes_actual': mes_actual
    })


@login_required
def ingresar_presupuesto(request):
    
    if request.method == 'POST':
        form = PresupuestoForm(request.POST)
        if form.is_valid():
            fecha = form.cleaned_data['fecha']
            cantidad = form.cleaned_data['cantidad']

            presupuesto = PresupuestoMensual(fecha=fecha, cantidad=cantidad, usuario=request.user)
            presupuesto.save()

            return redirect('mi_gestor:home')
    else:
        form = PresupuestoForm()

    return render(request, 'ingresar_presupuesto.html', {'form': form})


@login_required
def agregar_gasto(request):
    
    if request.method == 'POST':
        form = AgregarGastoForm(request.POST)
        if form.is_valid():
            gasto = form.save(commit=False)
            gasto.usuario = request.user
            gasto.save()

            return redirect('mi_gestor:home')
    else:
        form = AgregarGastoForm()

    return render(request, 'agregar_gasto.html', {'form': form})


@login_required
def eliminar_gasto(request, gasto_id):
    
    mes_actual = datetime.date.today().replace(day=1)
    gastos = GastoMensual.objects.filter(usuario=request.user, fecha__month=mes_actual.month, fecha__year=mes_actual.year).order_by('fecha')
    if request.method == 'POST':
        gasto_id = request.POST.get('gasto_id')
        gasto = get_object_or_404(GastoMensual, id=gasto_id)
        gasto.delete()
        return redirect('mi_gestor:home')
    else:
        return render(request, 'eliminar_gasto.html', {'gastos': gastos, 'gasto_id': gasto_id})


@login_required
def meses_previos(request):
    
    fecha_actual = datetime.date.today()
    year_actual = fecha_actual.year
    month_actual = fecha_actual.month
    
    gastos_meses_anteriores = GastoMensual.objects.filter(fecha__year=year_actual, fecha__month__lt=month_actual).order_by('-fecha')
    
    meses_previos = {}
    for gasto in gastos_meses_anteriores:
        fecha = gasto.fecha.strftime('%B, %Y')
        if fecha not in meses_previos:
            meses_previos[fecha] = []
        meses_previos[fecha].append(gasto)
    
    return render(request, 'meses_previos.html', {'meses_previos': meses_previos})

mi_gestor/templates/agregar_gasto.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Agregar Gasto</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'agregar_gasto_style.css' %}">
</head>
<body>

    <h2>Agregar Gasto</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Agregar Gasto</button>
    </form>
</body>
</html>

mi_gestor/templates/eliminar_gasto.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Eliminar Gasto</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'eliminar_gasto_style.css' %}">
</head>
<body>
    <h1>Eliminar Gasto</h1>
    <form action="{% url 'mi_gestor:eliminar_gasto' gasto_id %}" method="post">
        {% csrf_token %}
        <p>Selecciona el gasto que deseas eliminar:</p>
        {% for gasto in gastos %}
            <label>
                <input type="radio" name="gasto_id" value="{{ gasto.id }}">
                {{ gasto.descripcion }} - {{ gasto.cantidad }}
            </label><br>
        {% endfor %}
        <button type="submit">Eliminar</button>
    </form>
</body>
</html>

mi_gestor/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'home_style.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
</head>

<body>

    <div class="header">
        <div class="logo-left">
            <img src="{% static 'img/logo2.png' %}" width="400px">
        </div>
        <h2 class="circle">iSave</h2>
        <div class="logo-right">
            <img src="{% static 'img/logo2.png' %}" width="400px">
        </div>
    </div>

    <div class="sidebar">
        <h2 class="title-menu">Menú</h2>
        <ul>
            <li><a href="{% url 'mi_gestor:ingresar_presupuesto' %}">Ingresar Presupuesto</a></li>
            <li><a href="{% url 'mi_gestor:agregar_gasto' %}">Agregar Gasto</a></li>
            <li><a href="{% url 'mi_gestor:eliminar_gasto' gastos.0.id %}">Eliminar Gasto</a></li>
            <li><a href="{% url 'mi_gestor:meses_previos' %}">Meses Previos</a></li>
        </ul>
    </div>

     <div class="content">
        <div class="subheader">
            <div class="block">
                <h2 class="title2">Presupuesto Mensual</h2>
                <p>Presupuesto para este mes ({{ mes_actual|date:"F, Y"}}):<br>{{ presupuesto_mes_actual }} €</p>
                <p>Presupuesto restante para este mes ({{ mes_actual|date:"F, Y" }}):<br>{{ diferencia }} €</p>
            </div>
            <div class="block">
                <h2 class="title2">Gasto Mensual</h2>
                <p>Gastos acumulados este mes ({{ mes_actual|date:"F, Y" }}):<br>{{ total_mes_actual }} €</p>
            </div>
            <div class="image-front">
                <img src="{% static 'img/coins.png' %}" width="300px">
            </div>
        </div>

        <div class="table-container">
            <h2 class="title2">Historial de Gastos este Mes</h2>
            <button id="toggleButton">Mostrar Historial</button>
            <table id="tabla-gastos" border="1" style="display:none;">
                <thead>
                    <tr>
                        <th>Fecha</th>
                        <th>Categoría</th>
                        <th>Descripción</th>
                        <th>Cantidad</th>
                    </tr>
                </thead>
                <tbody>
                    {% for gasto in gastos %}
                    <tr>
                        <td>{{ gasto.fecha }}</td>
                        <td>{{ gasto.categoria }}</td>
                        <td>{{ gasto.descripcion }}</td>
                        <td>{{ gasto.cantidad }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    <script src="{% static 'toggle.js' %}"></script>

</body>
</html>

mi_gestor/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>
<body>

    <div class="container" id="container">
        <div class="form-container sign-in">
            <form method="post">
                {% csrf_token %}
                <h1>Iniciar Sesión</h1>

                <input type="text" name="username" placeholder="Nombre de usuario">
                <input type="password" name="password" placeholder="Contraseña">
                <a href="#" >¿Has olvidado tu contraseña?</a>
                <button type="submit">Iniciar Sesión</button>
            </form>
        </div>
        <div class="form-container sign-up">
            <form method="post">
                {% csrf_token %}
                <h1>Crear Cuenta</h1>

                <input type="text" placeholder="Usuario">
                <input type="email" placeholder="Email">
                <input type="password" placeholder="Contraseña">
                <button type="submit" class="toggle-rigth">Registrarse</button>
            </form>
        </div>
        <div class="toggle-container">
            <div class="toggle">
                <div class="toggle-panel toggle-left">
                    <h1>¡Hola!</h1>
                    <p>Ingresa tu nombre de usuario y contraseña para poder acceder</p>
                    <button id="loginBtn" class="toggle-left">Iniciar sesión</button>
                </div>
                <div class="toggle-panel toggle-right">
                    <h1>¡Bienvenido!</h1>
                    <p>Regístrate con tus datos personales para poder acceder al gestor de gastos</p>
                    <button id="registerBtn" class="toggle-right">Registrarse</button>
                </div>
            </div>
        </div>
    </div>

    <script src="{% static 'script.js' %}"></script>
</body>
</html>

mi_gestor/templates/ingresar_presupuesto.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ingresar/Editar Presupuesto</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'ingresar_presupuesto_style.css' %}">
</head>
<body>

    <h2>Ingresar o Editar Presupuesto Mensual</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar Presupuesto</button>
    </form>
</body>
</html>

mi_gestor/templates/meses_previos.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Meses Previos</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'meses_previos_style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>

<body>

<h1>Meses Anteriores</h1>

<div class="container">
    {% for mes, gastos in meses_previos.items %}
        <div class="mes-container">
            <button class="toggle-btn">{{ mes }}</button>
            <div class="gastos" style="display: none;">
                <p>Presupuesto: {{ datos_mes.presupuesto }}</p>
                <ul>
                    {% for gasto in gastos %}
                        <li>{{ gasto.fecha }} - {{ gasto.descripcion }} - {{ gasto.cantidad }}</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    {% endfor %}
</div>

<script>
    $(document).ready(function() {
        $('.toggle-btn').click(function() {
            $(this).next('.gastos').slideToggle();
        });
    });
</script>

</body>
</html>